name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Python 설정
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: 빌드 및 배포
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/* 