name: Run Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      script_name:
        description: '실행할 스크립트 이름'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - lint
          - test
          - build

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: 의존성 설치
        run: pip install -r requirements.txt
        
      - name: 스크립트 실행 권한 설정
        run: chmod +x scripts/*
        
      - name: 선택된 스크립트 실행
        run: |
          if [ "${{ github.event.inputs.script_name }}" = "all" ]; then
            for script in scripts/*.sh; do
              if [ -f "$script" ] && [ -x "$script" ]; then
                echo "Running $script"
                $script
              fi
            done
          else
            if [ -f "scripts/${{ github.event.inputs.script_name }}.sh" ]; then
              ./scripts/${{ github.event.inputs.script_name }}.sh
            else
              echo "Script scripts/${{ github.event.inputs.script_name }}.sh not found"
              exit 1
            fi
          fi