name: Run Scripts

on:
  workflow_dispatch:
    inputs:
      script_name:
        description: '실행할 스크립트 이름'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - lint
          - test
          - build
          - deploy

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt
          pip install build twine
          pip install -e .
          
      - name: 스크립트 실행 권한 설정
        run: chmod +x scripts/*
        
      - name: 선택된 스크립트 실행
        env:
          SCRIPT_NAME: ${{ github.event.inputs.script_name }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ "$SCRIPT_NAME" = "all" ]; then
            for script in scripts/*.sh; do
              if [ -f "$script" ]; then
                echo "Running $script"
                bash "$script"
              fi
            done
          elif [ -n "$SCRIPT_NAME" ]; then
            script_path="scripts/${SCRIPT_NAME}.sh"
            if [ -f "$script_path" ]; then
              echo "Running $script_path"
              bash "$script_path"
            else
              echo "Error: Script $script_path not found"
              exit 1
            fi
          else
            echo "Error: No script name provided"
            exit 1
          fi